version: "3.8"

services:
  analytic-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analytic-service
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    environment:
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_URL: ${CLICKHOUSE_URL}
      SPRING_DATASOURCE_USERNAME: ${CLICKHOUSE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${CLICKHOUSE_DRIVER}

      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL}
      SPRING_KAFKA_PROPERTIES_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM}
      SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG: ${KAFKA_SASL_JAAS}
      SPRING_KAFKA_CONSUMER_GROUP_ID: ${KAFKA_CONSUMER_GROUP_ID}
      SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: ${KAFKA_AUTO_OFFSET_RESET}
      SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: ${KAFKA_KEY_DESERIALIZER}
      SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: ${KAFKA_VALUE_DESERIALIZER}
